### ISSUE TITLE
Link to Food truck choices

### ISSUE THREAD

**Issue by hassanfa** [ScilifelabDataCentre/lunch-menu#13]
There are two websites that have information about foodtrucks on campus: http://www.sthlmstreetlunch.com/ or https://www.hittatrucken.se/#/ 

There are usually two food trucks in campus Solna, I don't know about others.

Thank you for this awesome tool!

**Comment by talavis** [comment]
The first page has no data that is easy to parse (only an image), while latter page seems to be broken (`Google Maps JavaScript API error: RefererNotAllowedMapError`)

**Comment by talavis** [comment]
I added a link in #28 which is hopefully live soonish.
